blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/francesco-oghabi/hetzner-server-terraform/security/advisories/new
    about: Please report security vulnerabilities privately through GitHub Security Advisories
  - name: GitHub Discussions
    url: https://github.com/francesco-oghabi/hetzner-server-terraform/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/francesco-oghabi/hetzner-server-terraform/blob/main/README.md
    about: Read the comprehensive documentation and guides