output "backup_user_private_key" {
  description = "Private SSH key for the backup user (only if generated by Terraform)"
  value       = local.backup_private_key
  sensitive   = true
}

output "backup_user_public_key" {
  description = "Public SSH key for the backup user"
  value       = local.backup_public_key
}

output "connection_command" {
  description = "SSH command to connect and perform backup"
  value       = "ssh dbbackup@${var.bastion_public_ip} \"database_name\" > dump.sql"
}

output "usage_instructions" {
  description = "Instructions for using the backup service"
  value = <<-EOT
    Database Backup Service Setup Complete!

    To perform a database backup from your local machine:

    1. Save the private SSH key (available in Terraform output 'backup_user_private_key')
       to a file, e.g., ~/.ssh/dbbackup_key

    2. Set correct permissions:
       chmod 600 ~/.ssh/dbbackup_key

    3. Perform a backup:
       ssh -i ~/.ssh/dbbackup_key dbbackup@${var.bastion_public_ip} "database_name" > dump.sql

    4. Perform a compressed backup:
       ssh -i ~/.ssh/dbbackup_key dbbackup@${var.bastion_public_ip} "database_name" | gzip > dump.sql.gz

    5. List available databases:
       ssh -i ~/.ssh/dbbackup_key dbbackup@${var.bastion_public_ip} "--list-databases"

    Allowed databases: ${local.allowed_dbs_list}

    Notes:
    - The backup user has read-only access to the databases
    - All backup operations are logged to /var/log/dbbackup/access.log on the bastion
    - You can only execute the backup command, no interactive shell access
  EOT
}